export const COUNTRIES: { id: string; name: string }[] = [
  { id: 'Afghanistan', name: 'Afghanistan' },
  { id: 'Albania', name: 'Albania' },
  { id: 'Algeria', name: 'Algeria' },
  { id: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina' },
  { id: 'China', name: 'China' },
  { id: 'Croatia', name: 'Croatia' },
  { id: 'Eritrea', name: 'Eritrea' },
  { id: 'Ethiopia', name: 'Ethiopia' },
  { id: 'Finland', name: 'Finland' },
  { id: 'France', name: 'France' },
  { id: 'Germany', name: 'Germany' },
  { id: 'Greece', name: 'Greece' },
  { id: 'Guinea', name: 'Guinea' },
  { id: 'Hungary', name: 'Hungary' },
  { id: 'India', name: 'India' },
  { id: 'Iran', name: 'Iran' },
  { id: 'Iraq', name: 'Iraq' },
  { id: 'Italy', name: 'Italy' },
  { id: 'Kosovo', name: 'Kosovo' },
  { id: 'Lebanon', name: 'Lebanon' },
  { id: 'Libya', name: 'Libya' },
  { id: 'Morocco', name: 'Morocco' },
  { id: 'Nigeria', name: 'Nigeria' },
  { id: 'North Macedonia', name: 'North Macedonia' },
  { id: 'Norway', name: 'Norway' },
  { id: 'Pakistan', name: 'Pakistan' },
  { id: 'Poland', name: 'Poland' },
  { id: 'Romania', name: 'Romania' },
  { id: 'Russia', name: 'Russia' },
  { id: 'Serbia', name: 'Serbia' },
  { id: 'Somalia', name: 'Somalia' },
  { id: 'Spain', name: 'Spain' },
  { id: 'Sudan', name: 'Sudan' },
  { id: 'Syria', name: 'Syria' },
  { id: 'Thailand', name: 'Thailand' },
  { id: 'Tunisia', name: 'Tunisia' },
  { id: 'Turkey', name: 'Turkey' },
  { id: 'Ukraine', name: 'Ukraine' },
  { id: 'United Kingdom', name: 'United Kingdom' },
  { id: 'United States', name: 'United States' },
  { id: 'Vietnam', name: 'Vietnam' },
]
