import path from 'node:path'
import { readFile } from 'node:fs/promises'
import type { ComponentDoc } from 'react-docgen-typescript'

/**
 * Reads the component docs generated by `nx run docgen:generate`
 * (tools/docgen/src/generate.ts) instead of running the (expensive)
 * react-docgen-typescript extraction itself. That extraction is shared with
 * apps/storybook and cached by Nx — see tools/docgen/src/generate.ts for
 * the actual parsing/enrichment logic, which used to live here.
 *
 * Kept registered under the same plugin name (`docusaurus-plugin-react-docgen-typescript`)
 * and still calling `setGlobalData`, so apps/docs/src/components/PropsTable.tsx
 * needs no changes at all.
 */
export default function customDocgenPlugin() {
  return {
    name: 'docusaurus-plugin-react-docgen-typescript',
    async loadContent(): Promise<ComponentDoc[]> {
      const jsonPath = path.join(
        __dirname,
        '../../dist/tools/docgen/component-docs.json',
      )
      const raw = await readFile(jsonPath, 'utf-8')
      return JSON.parse(raw)
    },
    configureWebpack(config) {
      return {
        resolve: {
          alias: {
            '@docgen': path.join(
              config.resolve.alias['@generated'],
              'docusaurus-plugin-react-docgen-typescript',
              'default',
            ),
          },
        },
      }
    },
    async contentLoaded({ content, actions }) {
      const { setGlobalData } = actions
      setGlobalData(content)
    },
  }
}
