export const options = [
  'Apple',
  'Banana',
  'Kiwi',
  'Elderflower',
  'Nectarine',
  'Watermelon',
  'Pineapple',
  'Apricot',
  'Cloudberry',
  'Mango',
  'Strawberry',
  'Blueberry',
  'Raspberry',
  'Blackberry',
  'Cherry',
  'Peach',
  'Plum',
  'Grape',
  'Orange',
  'Lemon',
  'Lime',
  'Coconut',
  'Fig',
  'Papaya',
  'Guava',
  'Pomegranate',
  'Dragonfruit',
  'Starfruit',
  'Passionfruit',
].map(fruit => ({
  name: fruit,
  id: fruit.toLocaleLowerCase(),
}))

export const optionsWithSections = [
  {
    name: 'Vegetables',
    children: [
      { name: 'Carrot', id: 'carrot' },
      { name: 'Broccoli', id: 'broccoli' },
      { name: 'Spinach', id: 'spinach' },
      { name: 'Potato', id: 'potato' },
      { name: 'Tomato', id: 'tomato' },
    ],
  },
  { name: 'Fruits', children: options },
]
