export declare const baseColors: {
    black: string;
    white: string;
    blackHover: string;
    whiteHover: string;
    gray10: string;
    gray20: string;
    gray30: string;
    gray40: string;
    gray50: string;
    gray60: string;
    gray70: string;
    gray80: string;
    gray90: string;
    gray100: string;
    gray110: string;
    gray120: string;
    gray130: string;
    gray140: string;
    gray150: string;
    gray160: string;
    gray170: string;
    gray180: string;
    gray190: string;
    gray200: string;
    blue10: string;
    blue20: string;
    blue40: string;
    blue60: string;
    blue80: string;
    blue90: string;
    blue100: string;
    blue140: string;
    blue170: string;
    purple80: string;
    purple140: string;
    red100: string;
    signalBlue10: string;
    signalBlue100: string;
    signalGreen20: string;
    signalGreen30: string;
    signalGreen100: string;
    signalYellow10: string;
    signalYellow100: string;
    signalRed20: string;
    signalRed30: string;
    signalRed80: string;
    signalRed100: string;
    signalRed160: string;
    signalRed180: string;
};
export declare const typography: {
    fontFamily: string;
    lineHeight10: number;
    lineHeight20: number;
    lineHeight30: number;
    lineHeight40: number;
    lineHeight50: number;
    lineHeight60: number;
    lineHeight70: number;
    lineHeight80: number;
    lineHeight90: number;
    lineHeight100: number;
    fontSize10: string;
    fontSize20: string;
    fontSize30: string;
    fontSize40: string;
    fontSize50: string;
    fontSize60: string;
    fontSize70: string;
    fontSize80: string;
    fontSize90: string;
    fontSize100: string;
    weightThin: number;
    weightExtraLight: number;
    weightLight: number;
    weightRegular: number;
    weightMedium: number;
    weightSemiBold: number;
    weightBold: number;
    weightExtraBold: number;
    weightBlack: number;
};
export declare const spacing: {
    '10': string;
    '20': string;
    '30': string;
    '40': string;
    '50': string;
    '60': string;
    '70': string;
    '80': string;
    '90': string;
    '100': string;
    '110': string;
    '120': string;
};
export declare const states: {
    focus: string;
};
export declare const transitions: {
    slow: string;
    normal: string;
    fast: string;
};
export declare const windowSizes: {
    md: number;
    lg: number;
    xl: number;
};
export declare const breakpoints: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
    forcedColorsMode: string;
    darkMode: string;
    prefersReducedMotion: string;
};
export declare const semantic: {
    background: string;
    backgroundHover: string;
    backgroundInverse: string;
    layer01: string;
    layerHover01: string;
    layerSelected01: string;
    layerSelectedHover01: string;
    layer02: string;
    layerHover02: string;
    layerSelected02: string;
    layerSelectedHover02: string;
    layerAccent01: string;
    layerAccentHover01: string;
    layerAccentSelected01: string;
    layerAccent02: string;
    layerAccentHover02: string;
    layerAccentSelected02: string;
    brandPrimary: string;
    borderPrimary: string;
    borderSecondary: string;
    borderSubtle: string;
    borderTertiary: string;
    /**
     * @deprecated Deprecated in 8.2.0. Use `supportBorderWarning` instead.
     * @type {string}
     */
    borderInvalid: string;
    borderDisabled: string;
    field01: string;
    fieldHover01: string;
    fieldActive01: string;
    field02: string;
    fieldHover02: string;
    fieldActive02: string;
    fieldDisabled: string;
    fieldSkeleton: string;
    iconPrimary: string;
    iconSecondary: string;
    iconTertiary: string;
    iconInverse: string;
    iconOnColor: string;
    iconDisabled: string;
    iconSuccess: string;
    iconInfo: string;
    iconWarning: string;
    iconImportant: string;
    linkEnabled: string;
    linkHover: string;
    linkPressed: string;
    linkVisited: string;
    supportBorderSuccess: string;
    supportBorderInfo: string;
    supportBorderImportant: string;
    supportBorderWarning: string;
    supportBackgroundSuccess: string;
    supportBackgroundSuccessHover: string;
    supportBackgroundInfo: string;
    supportBackgroundImportant: string;
    supportBackgroundWarning: string;
    supportBackgroundWarningHover: string;
    textPrimary: string;
    textSecondary: string;
    textTertiary: string;
    textOnColor: string;
    textInverse: string;
    textDisabled: string;
    /**
     * @deprecated Deprecated in 8.4.0 - Please use textWarning instead.
     */
    textInvalid: string;
    textWarning: string;
    textPlaceholder: string;
    buttonBackgroundPrimary: string;
    buttonBackgroundPrimaryHover: string;
    buttonBackgroundPrimaryActive: string;
    buttonBackgroundSecondary: string;
    buttonBackgroundSecondaryHover: string;
    buttonBackgroundSecondaryActive: string;
    buttonBackgroundTertiaryHover: string;
    buttonBackgroundTertiaryActive: string;
    buttonBackgroundDanger: string;
    buttonBackgroundDangerHover: string;
    buttonBackgroundDangerActive: string;
    buttonBackgroundDisabled: string;
    buttonBackgroundSkeleton: string;
    buttonBorderSecondary: string;
    logoPrimary: string;
    menuItemBackgroundHover: string;
    menuItemBackgroundSelected: string;
};
export declare const zIndex: {
    base: number;
    above: number;
    modal: number;
    toast: number;
    skipToContent: number;
};
