name: 'Cleanup PR Preview'

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  cleanup:
    name: Remove PR preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Remove preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/docs
          pages-base-url: 'designsystem.migrationsverket.se'
