name: Code - Lint, test and build packages

env:
  HUSKY: 0

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint, test and build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint, test and build packages
        run: npx nx run-many --targets=lint,stylelint,test,build --projects=components,theme
