name: Code - Test and Build Components

env:
  HUSKY: 0

on:
  pull_request:
    branches: ['main', 'release/**']

jobs:
  build:
    name: Test, Lint and Build Component Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci --omit-dev
      - run: npx nx run-many -t lint,stylelint,test,build --projects=components
