name: DocWeb - Deploy PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Build website
        if: github.event.action != 'closed'
        run: npx nx run docs:build --minify=false --outputPath=build
      - name: Build storybook
        if: github.event.action != 'closed'
        run: npx nx run ui:build-storybook:ci

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: main
