name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Select which projects to publish'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - components
          - theme
          - table-styles
          - datepicker-styles
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_CONFIG_PROVENANCE: true

jobs:
  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Publish all
        if: ${{ inputs.projects == 'all' }}
        run: npx nx release publish
        shell: bash

      - name: Publish one
        if: ${{ ! inputs.projects == 'all' }}
        run: npx nx release publish -p ${{ inputs.projects }}
        shell: bash
