name: 'Publish'

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    tags:
      - '*@v*.*.*'

jobs:
  publish-to-npm:
    uses: migrationsverket/midas/.github/workflows/publish-to-npm.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-docs:
    if: ${{ contains(github.ref_name, 'components@') }}
    uses: migrationsverket/midas/.github/workflows/publish-docs.yml@main
