name: 'Visual Testing (Chromatic)'

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - feat/*
      - feature/*
      - fix/*
      - bugfix/*

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          buildCommand: npx nx run storybook:build:ci
          outputDir: dist/docs/storybook
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # enables turbosnap
          autoAcceptChanges: 'main'
